### ISSUE TITLE
Optimize performance

### ISSUE THREAD

**Issue by ediooo** [sudosilico/sample-diffusion#12]
I just started rendering my first files and I am wondering if there are options to optimize performance for speed without sacrificing quality.

I am generating variations on a 13 second input file and with the following settings it takes 6 hours to render 4 wav files on my 16 core 3,2 gHz Mac Pro with a ton of ram and AMD Radeon Pro Vega II with 32 GB.

python generate.py --input "audio_in/in.wav" --input_sr 48000 --samples 4 --batches 1 --steps 170 --length_multiplier 15 --noise_level 1.0 --normalize --out_path "audio_out" --ckpt models/epoch=2303-step=634400.ckpt

Is reducing the steps and therefore reducing quality and increasing noise the only option?

Would reducing the model size using your trim-model script speed up the generation?

Any other tips on how I can optimize?
Thanks so much!

**Comment by sudosilico** [comment]
> AMD Radeon Pro Vega II with 32 GB

Unfortunately, CUDA is only supported on NVIDIA GPUs, so without MPS/Apple Silicon, you're left with using the CPU for your generations which is very slow. There may be a way to use AMD cards with Dance Diffusion at some point in the future using something like ROCm or onnx, but AMD support is unlikely to appear in this repo before the official Dance Diffusion notebooks/libraries, as neither @mrhyazinth nor myself have an AMD GPU, and porting Dance Diffusion to onnx is out of the scope of `sample-diffusion`.

> Is reducing the steps and therefore reducing quality and increasing noise the only option?

That's probably your only option for speeding things up. You can generate batches with a lower step count, pick the batches you like, and regenerate those seeds using a higher step count. Depending on the step sizes and the model, this usually works well for generating the "same sound" with less noise, although there is often some level of noise that you won't be able to remove by increasing the step count. I usually start with 25 steps and then refine the ones I like at 150.

Just keep in mind that the seed applies to the batch, not the sample, so if you like `sample_2.wav` from a given seed, you will need to generate a batch of at least two samples to get that sample again.

When you generate more than one batch in one command, the seed is incremented for subsequent batches.

**Comment by ediooo** [comment]
Thanks a lot for the insight @sudosilico!
I'll look into your tips to be more clever about my ressources, but unfortunately I'll probably have to shell out some $ for collab pro ressources if it is that slow on my machine.

As I was planning to get a new mac soon and would rather spend the money on that - Do you have a rough estimate how much faster it might potentially be on a current M2 macbook air vs my current mac pro?
