### ISSUE TITLE
audio_diffusion_pytorch

### ISSUE THREAD

**Issue by RichardJohnn** [sudosilico/sample-diffusion#23]
hello, when following the instructions and running `python cli.py`
I get an error saying ` No module named 'audio_diffusion_pytorch'`
If `pip install audio_diffusion_pytorch`
I get an error saying `ImportError: cannot import name 'T5Embedder' from 'audio_diffusion_pytorch'`

are there some missing steps required to run this? thank you

**Comment by sudosilico** [comment]
Should be fixed with the latest commit.
